# Generated by Django 4.0.2 on 2022-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': ('Рецепт',), 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='hexcolor',
            field=models.CharField(default='#ffffff', error_messages={'unique': 'Такой hex-цвет уже используется'}, help_text='Используйте формат "#fffff"', max_length=7, unique=True, verbose_name='HEX-цвет'),
        ),
    ]
